# Returns the list of files that should have been generated by a process, but were not.
library("magrittr")

#Define "not in": https://stackoverflow.com/questions/5831794/opposite-of-in
'%!in%' = function(x,y)!('%in%'(x,y))

filesNotRun = function(inDirec, outDirec, extension){
  #if typed extension first character is dot, remove it:
  if(substring(extension,1,1) == "."){
    extension = extension %>% substring(2)
  }
  inFiles = list.files(inDirec)
  inFiles = inFiles[grep(paste0("*.", extension), inFiles)]
  
  runFiles = list.files(outDirec)
  runFiles = runFiles[grep(paste0("*.",extension), runFiles)]
  
  notRun = list()
  i = 1
  for(inFile in inFiles){
    if(inFile %!in% runFiles){
      notRun[[i]] = inFile
      i = i + 1
    }
  }
  return(notRun)
}
